accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
  path("login/", views.login, name="login"),
  path("logout/", views.logout, name="logout"),
  path("signup/", views.signup, name="signup"),
  path("delete/", views.delete, name="delete"),
  path("update/", views.update, name="update"),
  path("password/", views.change_password, name="change_password"),
]

articles/urls.py
from django.urls import path
from . import views #.은 내 위치

app_name = 'articles'
urlpatterns = [

    path('', views.articles, name='articles'),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/comments/", views.comment_create, name="comment_create"),
    path(
        "<int:pk>/comments/<int:comment_pk>/delete/",
        views.comment_delete,
        name="comment_delete",
        ),


    path('data_throw/', views.data_throw, name='throw'),
    path('data_catch/', views.data_catch, name='catch'),
]

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from articles import views


# urlpatterns는 어떤 path로 들어왔을 때 어디로 보낼지
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),

    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
  path('', views.users, name = 'users'),
  path("profile/<str:username>/", views.profile, name = 'profile'),
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
  title = models.CharField(max_length=50)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True) #최초추가
  updated_at = models.DateTimeField(auto_now=True) #수정될때마다
  image = models.ImageField(upload_to="images/", blank=True)
  
  def __str__(self):
        return self.title

class Comment(models.Model):
  article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
  content = models.CharField(max_length=120)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def __str__(self):
    return self.content

articles/forms.py
from django import forms
from articles.models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__" # 모든 필드를 다 가져와서 모델로 만들어줘
        # exclude = ["title"] # 대신 그 중에 타이틀만 빼주고 (제외)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = "__all__"
        exclude = ("article", "user")

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods


def index(request):
  return render(request, "articles/index.html")

def articles(request):
  articles = Article.objects.all().order_by("-created_at")
  context = { "articles": articles,}
  return render(request, "articles/articles.html", context)

def detail(request, pk):
  article = get_object_or_404(Article, pk=pk)
  comment_form = CommentForm()
  comments = article.comments.all().order_by("-pk")
  context = { 
    "article": article,
    "comment_form" : comment_form,
    "comments" : comments
  }
  return render(request, "articles/detail.html", context)

@login_required
def create(request):
  if request.method == "POST":
      form = ArticleForm(request.POST, request.FILES)
      if form.is_valid():
          article = form.save()
          return redirect("articles:detail", article.id)
  else:
      form = ArticleForm()

  context = {"form": form,}
  return render(request, "articles/create.html", context)

def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect("articles:detail", article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        "form": form,
        "article": article,
    }
    return render(request, "articles/update.html", context)

@require_POST
def delete(request, pk):
  if request.user.is_authenticated:
    article = get_object_or_404(Article, pk=pk)
    article.delete()
  return redirect("articles:articles")

@require_POST
def comment_create(request, pk):
    article = get_object_or_404(Article, pk=pk)
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.article = article
        comment.save()
    return redirect("articles:detail", article.pk)


@require_POST
def comment_delete(request, pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment.delete()
    return redirect("articles:detail", pk)





def data_throw(request):
  return render(request, "articles/data_throw.html")

def data_catch(request):
  message = request.GET.get("message")
  context = {
      "message" : message,
		}
  return render(request, "articles/data_catch.html", context)

articles/templates/articles/articles.html
{% extends 'base.html' %} 

{% block content %}
  <h1> articles </h1>

  {% if request.user.is_authenticated %}
    <a href="{% url 'articles:create' %}">
      <button> 새로운 글 작성</button>
    </a>
  {% else %}
    <a href="{% url 'accounts:login' %}"> 로그인하고 글 작성하기 </a>
  {% endif %}
  
  <ul>
    {% for article in articles %}
      <li>
        <a href="{% url 'articles:detail' article.pk %}">
        <p>글 번호 : {{ article.id }}</p>
        <p>글 제목 : {{ article.title }}</p>
        </a>
        <hr>
      </li>
    {% endfor %}
  </ul>

{% endblock content %}

articles/templates/articles/create.html
{% extends 'base.html' %} 

{% block content %}
  <h1>New Article</h1>

  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">저장</button>
  </form>

  <a href="{% url 'articles:articles' %}">목록 으로</a>

{% endblock content %}

articles/templates/articles/data_catch.html
{% extends 'base.html' %} 

{% block content %}
  <h1> data catch </h1>
  
  <div>
    <h2>Current Data</h2>
    <p>Current data is: {{ message }}</p>
  </div>

  <a href = "{% url 'articles:throw' %}"> 데이터 던지러 가기 </a> 

{% endblock content %}

articles/templates/articles/data_throw.html
{% extends 'base.html' %} 

{% block content %}
  <h1> data throw </h1>
    <form action="{% url 'articles:catch' %}" method="GET">
      
      <label for = 'message'> 데이터 입력 </label>
      <input type = 'text' id = 'message' name='message'>

      <button type = "submit"> 전송 </button>
    
    </form>
    <a href = "{% url 'index' %}"> index </a> 
{% endblock content %}

articles/templates/articles/detail.html
{% extends "base.html" %}

{% block content %}

    <h2>글 상세 페이지</h2>
    <p>제목: {{ article.title }}</p>

    {% if article.image %}
        <img src="{{ article.image.url }}">
    {% endif %}

    <p>내용: {{ article.content }}</p>
    <p>작성일시: {{ article.created_at }}</p>
    <p>수정일시: {{ article.updated_at }}</p>

    <a href="{% url 'articles:articles' %}">목록보기</a>
    <a href="{% url 'articles:update' article.pk %}">
        <button>수정하기</button>
    </a>

    <form action="{% url 'articles:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="삭제">
    </form>

    <br>
    <hr>
    <h3>댓글 {{ comment|length }}개</h3>
    <form action="{% url "articles:comment_create" article.pk %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" value="댓글작성">
    </form>

    {% for comment in comments %}
    <ul>
        <li>{{ comment.content }}</li>
        <form action="{% url "articles:comment_delete" article.pk comment.pk%}" method="POST">
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    </ul>
    {% endfor %}

{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %} 
{% load static %}

{% block content %}
    <h1> INDEX </h1>

    <img src = "{% static 'articles/bear_image.png' %}" alt="">
    <br>
    <a href = "{% url 'articles:articles' %}"> 글 목록 </a><br>
    <a href = "{% url 'articles:throw' %}"> throw 이동 </a><br>
    <a href = "{% url 'users:users' %}"> users 이동 </a> 
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %} 

{% block content %}
  <h1>Edit Article</h1>

  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">수정</button>
  </form>

  <a href="{% url 'articles:detail' article.pk %}">이전으로</a>

{% endblock content %}