accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
  path("login/", views.login, name="login"),
  path("logout/", views.logout, name="logout"),
  path("signup/", views.signup, name="signup"),
  path("delete/", views.delete, name="delete"),
  path("update/", views.update, name="update"),
  path("password/", views.change_password, name="change_password"),
]

my_first_pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

from articles import views


# urlpatterns는 어떤 path로 들어왔을 때 어디로 보낼지
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),

    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('accounts.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
  path('', views.users, name = 'users'),
  path("profile/<str:username>/", views.profile, name = 'profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>

    {% block head %}{% endblock head %}
</head>
<body>

  <div class="navbar">
    {% if request.user.is_authenticated %}
      <h3>안녕하세요, {{ user }}님</h3>
      <form action="{% url 'accounts:logout' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="로그아웃"></input>
      </form>

      <a href="{% url 'accounts:update'%}">회원정보수정</a>

      <form action="{% url 'accounts:delete' %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="회원탈퇴"></input>
      </form>
    {% else %}
      <a href="{% url 'accounts:login'%}">로그인</a>
      <a href="{% url 'accounts:signup'%}">회원가입</a>
    {% endif %}
  </div>

  <div class="container">
    {% block content %}
    {% endblock content %}
  </div>

</body>
</html>